services:
  app:
    image: php:8.2-fpm
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www/html
    depends_on:
      - minio

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data: